[package]
name = "lvoytek_advent_of_code_2021"
version = "2.1.0"
authors = ["Lena Voytek"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name = "sonar_sweep"
path = "day1/sonar_sweep/main.rs"

[[bin]]
name = "sonar_window"
path = "day1/sonar_window/main.rs"

[[bin]]
name = "dive_position"
path = "day2/dive_position/main.rs"
