[package]
name = "lvoytek_advent_of_code_2021"
version = "1.0.0"
authors = ["Lena Voytek"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name = "sonar_sweep"
path = "day1/sonar_sweep/main.rs"
